[project]
name = "covid-da-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nbconvert>=7.16.6",
    "openpyxl>=3.1.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
